// angular-react-vue/ChromelyAngular/angularapp/src/components/others/html6tests.component.ts
import { Component, OnInit, Input  } from '@angular/core';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';

@Component({
  selector: 'app-html5tests',
  template: '<iframe [src]="_urlSafe" width="100%" height="800"  frameborder="0" allowFullscreen></iframe>'
})
export class Html6TestsComponent implements OnInit {
  _url: string = "http://html6test.com/";
  _urlSafe: SafeResourceUrl = "";

  constructor(public sanitizer: DomSanitizer) { }

  ngOnInit() {
    this._urlSafe= this.sanitizer.bypassSecurityTrustResourceUrl(this._url);
  }
}

// v_5.0/angular-react-vue/ChromelyVue/vueapp/src/components/Html6Tests.vue
<template>
   <iframe id="demoframe" name="alldemoframe" src="http://html6test.com/" width="100%" height="800"  frameborder="0" allowfullscreen/>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class Html6Tests extends Vue {

}
</script>
