// v_5.1/angular-react-vue/ChromelyVue/vueapp/src/App.vue
<template>
    <div id="app">
        <nav class="navbar navbar-expand-sm navbar-light bg-faded">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Brand -->
            <a class="navbar-brand text-muted" href="#">Demos</a>


            <!-- Links -->
            <div class="collapse navbar-collapse justify-content-end" id="nav-content">
                <ul class="nav nav-pills">
                    <li class="nav-item">
                        <a class="nav-link"><router-link to="/">home</router-link></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"><router-link to="/tmdbmovies">tmdb movies</router-link></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"><router-link to="/todolist">todo list</router-link></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">basics</a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item"><router-link to="/msgrouter">Message Router Demo</router-link></a>
                            <a class="dropdown-item"><router-link to="/ajax">Ajax Demo</router-link></a>
                            <a class="dropdown-item"><router-link to="/javascriptdemo">Execute JavaScript Demo</router-link></a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item"><router-link to="/html5tests">HTML5 Tests</router-link></a>
                            <a class="dropdown-item"><router-link to="/html6tests">HTML6 Tests</router-link></a>
                            <a class="dropdown-item"><router-link to="/shakatests">Google Shaka Support Tests</router-link></a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:void(0);"><router-link to="/" @click="showDevTools">Show DevTools</router-link></a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="container-fluid">
            <div class="row">
                <div class="col-12 p-0">
                    <div class="text-center m-0  d-flex flex-column justify-content-center">
                        <router-view />
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    var chromelyService = require('../src/services/ChromelyService');

    export default {
        setup() {
            const showDevTools = () => {
                chromelyService.openExternalUrl('http://command.com/democontroller/showdevtools');
            }

            return {
                showDevTools
            }
        }
    }
</script>

<style>
    .navbar {
        background: none;
        box-shadow: none;
    }

    .navbar-brand {
        font-family: 'Palatino';
        font-style: italic;
        color: grey;
        font-size: 30px;
        margin: 0px;
    }

    iframe, object, embed {
        max-width: 100%;
    }
</style>

// angular-react-vue/ChromelyReact/reactapp/src/App.js
import React from "react";
import { Routes, Link, Route } from "react-router-dom";
import Home from "./components/Home";
import TmdbMovies from './components/TmdbMovies';
import TodoList from './components/TodoList';
import MessageRouterDemo from './components/MessageRouterDemo';
import AjaxXhrDemo from './components/AjaxXhrDemo';
import Html5Tests from './components/Html5Tests';
import Html6Tests from './components/Html6Tests';
import GoogleShakaTests from './components/GoogleShakaTests';
import JavasSriptDemo from './components/JavasSriptDemo';
import './App.css';

export default function App() {
    return (
      <div>

        <nav className="navbar navbar-expand-sm navbar-light bg-faded">
            <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
                <span className="navbar-toggler-icon"></span>
            </button>

            <a className="navbar-brand text-muted" href="#">Demos</a>

            <div className="collapse navbar-collapse justify-content-end">
                <ul className="nav nav-pills">
                    <li className="nav-item"><Link to={'/'} className="nav-link"> home </Link></li>
                    <li className="nav-item"><Link to={'/tmdbmovies'} className="nav-link"> tmdb movies </Link></li>
                    <li className="nav-item"><Link to={'/todolist'} className="nav-link"> todo list </Link></li>
                    <li className="nav-item dropdown">
                        <a className="nav-link dropdown-toggle" data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">basics</a>
                        <div className="dropdown-menu dropdown-menu-right">
                            <div className="dropdown-item"><Link to={'/msgrouter'} className="nav-link"> Message Router Demo </Link></div>
                            <div className="dropdown-item"><Link to={'/ajax'} className="nav-link"> Ajax Demo </Link></div>
                            <div className="dropdown-item"><Link to={'/javascriptdemo'} className="nav-link"> Execute JavaScript Demo </Link></div>
                            <div className="dropdown-divider"></div>
                            <div className="dropdown-item"><Link to={'/html5tests'} className="nav-link"> HTML5 Tests </Link></div>
                            <div className="dropdown-item"><Link to={'/html6tests'} className="nav-link"> HTML6 Tests </Link></div>
                            <div className="dropdown-item"><Link to={'/shakatests'} className="nav-link"> Google Shaka Support Tests </Link></div>
                            <div className="dropdown-divider"></div>
                            <div className="dropdown-item"><a href="http://command.com/democontroller/showdevtools" className="btn btn-link btn-sm" role="button" style={{ margin: '5px' }}>Show DevTools</a></div>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>

            <Routes>
                <Route exact path='/' element={< Home />} />
                <Route path='/tmdbmovies' element={< TmdbMovies /> } />
                <Route path='/todolist' element={< TodoList /> } />
                <Route path='/msgrouter' element={< MessageRouterDemo /> } />
                <Route path='/ajax' element={< AjaxXhrDemo /> } />
                <Route path='/javascriptdemo' element={< JavasSriptDemo /> } />
                <Route path='/html5tests' element={< Html5Tests /> } />
                <Route path='/html6tests' element={< Html6Tests /> } />
                <Route path='/shakatests' element={< GoogleShakaTests />} />
                <Route path="*" element={< Home />} />
        </Routes>
    </div>
  );
}
