// v_5.1/angular-react-vue/ChromelyReact/reactapp/src/components/Html5Tests.js
﻿const frameStyle = {
    width: '100%',
    height: '800px',
    frameborder: '0'
};

export default function Html5Tests() {
    return (
        <div>
            <div className="container-fluid">
                <div className="row">
                    <div className="col-12 p-0">
                        <div className="text-center m-0  d-flex flex-column justify-content-center">
                            <iframe id="demoframe" name="alldemoframe" src="https://html5test.com/" style={frameStyle} allowFullScreen />
                        </div>
                    </div>
                </div>
             </div>
        </div>
    );
}

// angular-react-vue/ChromelyVue/vueapp/src/components/Html5Tests.vue
<template>
   <iframe id="demoframe" name="alldemoframe" src="https://html5test.com/" width="100%" height="800"  frameborder="0" allowfullscreen/>
</template>


<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class Html5Tests extends Vue {

}
</script>
