// angular-react-vue/ChromelyReact/reactapp/src/components/TodoList.jsx
import React, { Component } from 'react';
import { messageRouterGet, openExternalUrl } from '../services/Chromely.Service.js';

const itemTextStyle = {
  'font-size': '24px',
  'text-align': 'center'
};

class BoundActiveRow extends React.Component {
  render() {
    const itemId = this.props.item.Id;
    return (
    <li className="list-group-item d-flex justify-content-between align-items-center"> 
      <div className="custom-control custom-switch">
        <input type="checkbox" className="custom-control-input"  id={this.props.item.Id + 'CheckboxTodoItem'} unchecked onClick={() => this.props.toggleTodoItem(itemId)}/>
        <label className="custom-control-label" for={this.props.item.Id + 'CheckboxTodoItem'}>{this.props.item.Todo}</label>
        </div>
        <span className="badge badge-secondary badge-pill"><a href='javascript:void(0);' onClick={() => this.props.deleteTodoItem(itemId)}>X</a></span>
    </li>
    )
  }
}

class BoundCompletedRow extends React.Component {
  render() {
    const itemId = this.props.item.Id;
    return (
    <li className="list-group-item d-flex justify-content-between align-items-center"> 
      <div className="custom-control custom-switch">
        <input type="checkbox" className="custom-control-input"  id={this.props.item.Id + 'CheckboxTodoItem'} checked onClick={() => this.props.toggleTodoItem(itemId)}/>
        <label className="custom-control-label" for={this.props.item.Id + 'CheckboxTodoItem'}><del>{this.props.item.Todo}</del></label>
        </div>
        <span className="badge badge-secondary badge-pill"><a href='javascript:void(0);' onClick={() => this.props.deleteTodoItem(itemId)}>X</a></span>
    </li>
    )
  }
}

class TodoList extends Component {

  constructor(props) {
    super(props);

    this.state = {
      todoText: '',
      todoItemsList: [],
      checkedAll: 0
    };

    this.todoTextChange = this.todoTextChange.bind(this);
    this.todoAddItem = this.todoAddItem.bind(this);
    this.toggleTodoItem = this.toggleTodoItem.bind(this);
    this.toggleAllTodoItems = this.toggleAllTodoItems.bind(this);
    this.deleteTodoItem = this.deleteTodoItem.bind(this);
  }

  getTodoList(reqType, id, todo, completed) {
    var parameters = {};
    parameters["name"] = reqType;
    parameters["id"] = id;
    parameters["todo"] = todo;
    parameters["completed"] = completed.toString();

    messageRouterGet('/todolistcontroller/items', parameters, this.onGetListsCallback, this);
  }

  onGetListsCallback(data, _self) {
    var dictList = [];
    for (var i = 0; i < data.length; i++) {

        var todoItem = data[i];
        
        var tempItem = {
          Id: todoItem.Id,
          Todo: todoItem.Todo,
          Completed:todoItem.Completed
        };

        dictList[todoItem.Id] = tempItem;
     };

     _self.setState({
        todoItemsList: dictList
    });
  }

  todoTextChange(event) {
    event.preventDefault();

    this.setState({todoText: event.target.value});
  }

  todoAddItem(event) {
    event.preventDefault();

    if (event.key === "Enter") {
      const { todoText } = this.state;
      this.getTodoList("add", "", todoText, 0);
      this.setState({todoText: ''});
    }
  }

  toggleTodoItem(itemId) {
    const { todoItemsList } = this.state;
    var dictList = todoItemsList;
    var todoItem = dictList[itemId];
    var completed = todoItem.Completed == 1 ? 0 : 1;
    dictList[itemId].Completed = completed;

    var url = "http://command.com/todolistcontroller/toggleactive?id=" + itemId + "&completed=" + completed.toString();
    console.log(url);
    openExternalUrl(url);

    this.setState({todoItemsList: dictList});
  }

  toggleAllTodoItems(event) {
    event.preventDefault();

    const { checkedAll } = this.state;
    var newCheckedAll = checkedAll == 1 ? 0 : 1;
    this.setState({checkedAll: newCheckedAll});
    this.getTodoList("toggleall", "", "", newCheckedAll);
  }

  deleteTodoItem(itemId) {
    this.getTodoList("delete", "" + itemId, "", "");
  }

  render() {

    const { todoText } = this.state;
    const { todoItemsList } = this.state;

    return (
      <div className="container-fluid">
          
          <div className="row col-12 justify-content-center">
                  <div className="col-8">
                          <div className="input-group">
                              <div className="input-group-prepend">
                                  <span className="input-group-text">
                                      <div className="custom-control custom-switch">
                                          <input type="checkbox" className="custom-control-input" id="checkboxSelectAllTodoItems" onClick={this.toggleAllTodoItems} />
                                          <label className="custom-control-label" for="checkboxSelectAllTodoItems"></label>
                                        </div>
                                  </span>
                          </div>
                          <input type="text" className="form-control" value={todoText} onChange={this.todoTextChange} onKeyUp={this.todoAddItem}  placeholder="What needs to be done?" style={itemTextStyle} />
                      </div>
                  </div>
          </div>

        {/* TODO Items List ---------- */} 
            <div className="row col-12 justify-content-center">
              <div className="col-8">
                <ul className="list-group">
                {todoItemsList.map((value, index) => {
                  if (value.Completed == 1) {
                  return <BoundCompletedRow toggleTodoItem={this.toggleTodoItem} deleteTodoItem={this.deleteTodoItem}  item={value}/>;
                  }
                  else {
                    return <BoundActiveRow toggleTodoItem={this.toggleTodoItem} deleteTodoItem={this.deleteTodoItem} item={value}/>;
                  }
                })}
                </ul>
              </div>
            </div>
        {/* End TODO Items List ---------- */} 

          <div className="row col-12 justify-content-center">
                  <div className="col-8">
                          <ul className="list-group">
                            <li className="list-group-item d-flex justify-content-between align-items-center">
                            <label>Chromely TODO List</label>
                              <button type="button" className="btn btn-link" onClick={() => this.getTodoList('all', '', '', '')} >All</button>
                              <button type="button" className="btn btn-link" onClick={() => this.getTodoList('allactive', '', '', '')} >Active</button>
                              <button type="button" className="btn btn-link" onClick={() => this.getTodoList('allcompleted', '', '', '')}  >Completed</button>
                              <button type="button" className="btn btn-link" onClick={() => this.getTodoList('clearcompleted', '', '', '')}  >Clear completed</button>
                            </li>
                          </ul>
                  </div>
          </div>
          
      </div>   
    );
  }
}

export default TodoList;

// angular-react-vue/ChromelyVue/vueapp/src/components/TodoList.vue
<template>
      <div class="container justify-content-center">
	  <div class="container-fluid">
          
          <div class="row col-12 justify-content-center">
                  <div class="col-8">
                          <div class="input-group">
                              <div class="input-group-prepend">
                                  <span class="input-group-text">
                                      <div class="custom-control custom-switch">
                                          <input type="checkbox" class="custom-control-input"  id="checkboxSelectAllTodoItems" v-model="checkedAll" @click="toggleAllTodoItems" />
                                          <label class="custom-control-label"  for="checkboxSelectAllTodoItems"></label>
                                        </div>
                                  </span>
                          </div>
                          <input type="text" class="form-control" v-model="todoText" v-on:keyup.enter="todoAddItem"   placeholder="What needs to be done?" style="font-size: 24px; text-align: center;" />
                      </div>
                  </div>
          </div>

        <!-- TODO Items List ---------- --> 
            <div class="row col-12 justify-content-center">
              <div class="col-8">
                <ul class="list-group">
		
                  <div  v-for="item in todoItemsList" :key="item.Id">
                    <li class="list-group-item d-flex justify-content-between align-items-center"> 
                      <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input"  v-bind:id="item.CheckboxId" v-bind:checked="item.ItemChecked" @click="() => { toggleTodoItem(item) }"/>
                        <label class="custom-control-label" v-bind:for="item.CheckboxId" v-html="item.TodoHtml"></label>
                        </div>
                        <span class="badge badge-secondary badge-pill"><a href='javascript:void(0);' @click="() => { deleteTodoItem(item.Id) }">X</a></span>
                    </li>
                  </div>

                </ul>
              </div>
            </div>
        <!-- End TODO Items List ---------- --> 

          <div class="row col-12 justify-content-center">
                  <div class="col-8">
                          <ul class="list-group">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                            <label>Chromely TODO List</label>
                              <button type="button" class="btn btn-link" @click="getTodoList('all', '', '', '')" >All</button>
                              <button type="button" class="btn btn-link"  @click="getTodoList('allactive', '', '', '')" >Active</button>
                              <button type="button" class="btn btn-link" @click="getTodoList('allcompleted', '', '', '')"  >Completed</button>
                              <button type="button" class="btn btn-link" @click="getTodoList('clearcompleted', '', '', '')" >Clear completed</button>
                            </li>
                          </ul>
                  </div>
          </div>
          
      </div>   
	</div>   
</template>


<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
var chromelyService = require('../services/ChromelyService');

type  TodoItem = {
    Id: string;
    Todo: string;
    TodoHtml: string,
    Completed: number;
    ItemChecked: boolean,
    CheckboxId: string
};

type Dict1 = { [key: string]: string };
type Dict2 = { [key: string]: TodoItem };

@Component
export default class TodoList extends Vue {

    todoText = '';
    checkedAll = false;
    todoItemsList: Dict2 = {};

  getTodoList(reqType:string, id:string, todo:string, completed: number) {
    const parameters: Dict1 = {};
    parameters["name"] = reqType;
    parameters["id"] = id;
    parameters["todo"] = todo;
    parameters["completed"] = completed.toString();

    chromelyService.messageRouterGetJson('/todolistcontroller/items', parameters, this.onGetListsCallback, this);
  }

  onGetListsCallback(res: any) {
    const dictList: Dict2 = {};
    for (var i = 0; i < res.length; i++) {

        var todoItem = res[i];
        
        var itemChecked = todoItem.Completed == 1 ? true : false;
        var delTagStart = todoItem.Completed == 1 ? "<del>" : "";
        var delTagEnd = todoItem.Completed == 1 ? "</del>" : "";

        var tempItem = {
          Key: todoItem.Id,
          Id: todoItem.Id + "",
          Todo: todoItem.Todo,
          TodoHtml: delTagStart + todoItem.Todo + delTagEnd,
          Completed:todoItem.Completed,
          ItemChecked: itemChecked,
          CheckboxId:"CheckboxTodoItem" + res[i].Id
        };

        dictList[todoItem.Id] = tempItem;
     };

    this.todoItemsList = dictList;
  }

  todoAddItem() {
    this.getTodoList("add", "", this.todoText, 0);
    this.todoText = "";
  }

  toggleTodoItem(item: any) {
    item.ItemChecked = !item.ItemChecked;
    this.checkedAll = false;
    
    var completed = item.ItemChecked ? 1 : 0;
    var delTagStart = item.ItemChecked ? "<del>" : "";
    var delTagEnd = item.ItemChecked ? "</del>" : "";
    item.TodoHtml = delTagStart + item.Todo + delTagEnd;

    var itemId = item.Id;
    var dictList = this.todoItemsList;
    var todoItem = dictList[itemId];
    dictList[itemId].Completed = completed;

    var url = "http://command.com/todolistcontroller/toggleactive?id=" + itemId + "&completed=" + completed.toString();
    chromelyService.openExternalUrl(url);

    this.todoItemsList = dictList;
  }

  toggleAllTodoItems() {
       console.log("this.checkedAll:" + this.checkedAll);
    var newCheckedAll = this.checkedAll ? 0 : 1;
    this.getTodoList("toggleall", "", "", newCheckedAll);
  }

  deleteTodoItem(itemId: string) {
    this.getTodoList("delete", itemId, "", 0);
  }
}
</script>
